# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app.pdf_to_image_pb2 as pdf__to__image__pb2


class PdfToImageServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.unary_unary(
                '/protos.PdfToImageService/Convert',
                request_serializer=pdf__to__image__pb2.PdfToImageRequest.SerializeToString,
                response_deserializer=pdf__to__image__pb2.PdfToImageResponse.FromString,
                )


class PdfToImageServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Convert(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PdfToImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=pdf__to__image__pb2.PdfToImageRequest.FromString,
                    response_serializer=pdf__to__image__pb2.PdfToImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.PdfToImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PdfToImageService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.PdfToImageService/Convert',
            pdf__to__image__pb2.PdfToImageRequest.SerializeToString,
            pdf__to__image__pb2.PdfToImageResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
