# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pdf_to_image.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pdf_to_image.proto',
  package='protos',
  syntax='proto3',
  serialized_options=b'Z\025.;pdf_to_image_protos',
  serialized_pb=b'\n\x12pdf_to_image.proto\x12\x06protos\"F\n\x11PdfToImageRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12#\n\x06\x66ormat\x18\x02 \x01(\x0e\x32\x13.protos.ImageFormat\"#\n\x12PdfToImageResponse\x12\r\n\x05pages\x18\x01 \x03(\x0c*6\n\x0bImageFormat\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04JPEG\x10\x01\x12\x07\n\x03PNG\x10\x02\x12\x07\n\x03SVG\x10\x03\x32W\n\x11PdfToImageService\x12\x42\n\x07\x43onvert\x12\x19.protos.PdfToImageRequest\x1a\x1a.protos.PdfToImageResponse\"\x00\x42\x17Z\x15.;pdf_to_image_protosb\x06proto3'
)

_IMAGEFORMAT = _descriptor.EnumDescriptor(
  name='ImageFormat',
  full_name='protos.ImageFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JPEG', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PNG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVG', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=139,
  serialized_end=193,
)
_sym_db.RegisterEnumDescriptor(_IMAGEFORMAT)

ImageFormat = enum_type_wrapper.EnumTypeWrapper(_IMAGEFORMAT)
UNKNOWN = 0
JPEG = 1
PNG = 2
SVG = 3



_PDFTOIMAGEREQUEST = _descriptor.Descriptor(
  name='PdfToImageRequest',
  full_name='protos.PdfToImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='protos.PdfToImageRequest.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='protos.PdfToImageRequest.format', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=100,
)


_PDFTOIMAGERESPONSE = _descriptor.Descriptor(
  name='PdfToImageResponse',
  full_name='protos.PdfToImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pages', full_name='protos.PdfToImageResponse.pages', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=137,
)

_PDFTOIMAGEREQUEST.fields_by_name['format'].enum_type = _IMAGEFORMAT
DESCRIPTOR.message_types_by_name['PdfToImageRequest'] = _PDFTOIMAGEREQUEST
DESCRIPTOR.message_types_by_name['PdfToImageResponse'] = _PDFTOIMAGERESPONSE
DESCRIPTOR.enum_types_by_name['ImageFormat'] = _IMAGEFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PdfToImageRequest = _reflection.GeneratedProtocolMessageType('PdfToImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _PDFTOIMAGEREQUEST,
  '__module__' : 'pdf_to_image_pb2'
  # @@protoc_insertion_point(class_scope:protos.PdfToImageRequest)
  })
_sym_db.RegisterMessage(PdfToImageRequest)

PdfToImageResponse = _reflection.GeneratedProtocolMessageType('PdfToImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _PDFTOIMAGERESPONSE,
  '__module__' : 'pdf_to_image_pb2'
  # @@protoc_insertion_point(class_scope:protos.PdfToImageResponse)
  })
_sym_db.RegisterMessage(PdfToImageResponse)


DESCRIPTOR._options = None

_PDFTOIMAGESERVICE = _descriptor.ServiceDescriptor(
  name='PdfToImageService',
  full_name='protos.PdfToImageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=195,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='Convert',
    full_name='protos.PdfToImageService.Convert',
    index=0,
    containing_service=None,
    input_type=_PDFTOIMAGEREQUEST,
    output_type=_PDFTOIMAGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PDFTOIMAGESERVICE)

DESCRIPTOR.services_by_name['PdfToImageService'] = _PDFTOIMAGESERVICE

# @@protoc_insertion_point(module_scope)
