# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binarizer.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='binarizer.proto',
  package='binarizer',
  syntax='proto3',
  serialized_options=b'\n/com.github.eitol.document_color_meter.binarizerB\016BinarizerProtoP\001Z\013.;binarizer',
  serialized_pb=b'\n\x0f\x62inarizer.proto\x12\tbinarizer\"]\n\x0f\x42inarizeRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12:\n\x13\x62inarization_method\x18\x02 \x01(\x0e\x32\x1d.binarizer.BinarizationMethod\"4\n\x10\x42inarizeResponse\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12\x10\n\x08out_path\x18\x02 \x01(\t*G\n\x12\x42inarizationMethod\x12\r\n\tUNDEFINED\x10\x00\x12\x0b\n\x07SAUVOLA\x10\x01\x12\x0b\n\x07NIBLACK\x10\x02\x12\x08\n\x04OTSU\x10\x03\x32R\n\tBinarizer\x12\x45\n\x08\x42inarize\x12\x1a.binarizer.BinarizeRequest\x1a\x1b.binarizer.BinarizeResponse\"\x00\x42P\n/com.github.eitol.document_color_meter.binarizerB\x0e\x42inarizerProtoP\x01Z\x0b.;binarizerb\x06proto3'
)

_BINARIZATIONMETHOD = _descriptor.EnumDescriptor(
  name='BinarizationMethod',
  full_name='binarizer.BinarizationMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAUVOLA', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NIBLACK', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTSU', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=179,
  serialized_end=250,
)
_sym_db.RegisterEnumDescriptor(_BINARIZATIONMETHOD)

BinarizationMethod = enum_type_wrapper.EnumTypeWrapper(_BINARIZATIONMETHOD)
UNDEFINED = 0
SAUVOLA = 1
NIBLACK = 2
OTSU = 3



_BINARIZEREQUEST = _descriptor.Descriptor(
  name='BinarizeRequest',
  full_name='binarizer.BinarizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='binarizer.BinarizeRequest.images', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binarization_method', full_name='binarizer.BinarizeRequest.binarization_method', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=123,
)


_BINARIZERESPONSE = _descriptor.Descriptor(
  name='BinarizeResponse',
  full_name='binarizer.BinarizeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='binarizer.BinarizeResponse.images', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='out_path', full_name='binarizer.BinarizeResponse.out_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=177,
)

_BINARIZEREQUEST.fields_by_name['binarization_method'].enum_type = _BINARIZATIONMETHOD
DESCRIPTOR.message_types_by_name['BinarizeRequest'] = _BINARIZEREQUEST
DESCRIPTOR.message_types_by_name['BinarizeResponse'] = _BINARIZERESPONSE
DESCRIPTOR.enum_types_by_name['BinarizationMethod'] = _BINARIZATIONMETHOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BinarizeRequest = _reflection.GeneratedProtocolMessageType('BinarizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _BINARIZEREQUEST,
  '__module__' : 'binarizer_pb2'
  # @@protoc_insertion_point(class_scope:binarizer.BinarizeRequest)
  })
_sym_db.RegisterMessage(BinarizeRequest)

BinarizeResponse = _reflection.GeneratedProtocolMessageType('BinarizeResponse', (_message.Message,), {
  'DESCRIPTOR' : _BINARIZERESPONSE,
  '__module__' : 'binarizer_pb2'
  # @@protoc_insertion_point(class_scope:binarizer.BinarizeResponse)
  })
_sym_db.RegisterMessage(BinarizeResponse)


DESCRIPTOR._options = None

_BINARIZER = _descriptor.ServiceDescriptor(
  name='Binarizer',
  full_name='binarizer.Binarizer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=252,
  serialized_end=334,
  methods=[
  _descriptor.MethodDescriptor(
    name='Binarize',
    full_name='binarizer.Binarizer.Binarize',
    index=0,
    containing_service=None,
    input_type=_BINARIZEREQUEST,
    output_type=_BINARIZERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BINARIZER)

DESCRIPTOR.services_by_name['Binarizer'] = _BINARIZER

# @@protoc_insertion_point(module_scope)
